apiVersion: apps/v1
kind: Deployment
metadata:
 name: loja-deployment
spec:
 selector:
   matchLabels:
     app: site
 replicas: 2
 template:
   metadata:
     labels:
       app: site
   spec:
     containers:
     - name: site
       image: helenanakamura/loja-virtual
       ports:
       - containerPort: 80
